"""Shim for an SQS queue."""

import logging
from itertools import batched
from time import localtime, sleep, strftime
from typing import List, Tuple
from uuid import uuid4

import boto3
from botocore.exceptions import ClientError
from common import SolverEnvironment
from common.constants import (
    SQS_BATCH_SIZE,
    SQS_MAX_MESSAGES_PER_CALL,
    SQS_MAX_WAIT_TIME_SECS,
)

################################################################################


class SqsQueueException(Exception):
    """Exception for SqsQueue errors"""


class QueueMessage:
    """Class to represent an SQS message.

    In `boto3`, SQS messages are dictionaries.
    For their format, see:
        https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/sqs/client/receive_message.html
    """

    def __init__(self, msg: dict, sqs_client, queue_url):
        self.logger = logging.getLogger("QueueMessage")
        self.logger.setLevel(logging.DEBUG)
        self.sqs_client = sqs_client
        self.queue_url = queue_url
        self.msg = msg

    def get_handle(self) -> str:
        """Returns the message's receipt handle (a queue-unique ID)."""
        return self.msg["ReceiptHandle"]

    def read(self) -> str:
        """Reads the body of the SQS message. Ignored all the metadata."""
        # TODO: Test to ensure that a message containing a "JSON" is still a string, and not a Python object
        return self.msg["Body"]

    def delete(self) -> str:
        """Deletes this message from the SQS queue. Returns the message text.

        If an exception is encountered, raises an `SqsQueueException`.
        """
        handle = self.get_handle()
        self.logger.info("Deleting message with receipt handle: %s", handle)
        try:
            self.sqs_client.delete_message(
                QueueUrl=self.queue_url,
                ReceiptHandle=handle,
            )
        except ClientError as e:
            self.logger.error("Failed to delete message from SQS queue")
            self.logger.exception(e)
            raise SqsQueueException(f"Failed to delete message on SQS queue at URL {self.queue_url}")
        else:
            return self.read()


class LocalSqsQueue:
    def __init__(self, queue_name: str):
        self.queue_name = queue_name
        self.queue_url = queue_name
        # These are "unreceived" from the caller's point of view
        self.messages: list[str] = []
        # Keys are the handles generated by __get_new_message_handle()
        self.received_messages: dict = {}
        self.num_messages_received_by_caller = 0

    def __get_new_message_handle(self):
        n = self.num_messages_received_by_caller
        self.num_messages_received_by_caller += 1
        return f"msg-{n}"

    def get_queue_url(self) -> str:
        return self.queue_url

    def raise_exception_if_url_not_matching(self, QueueUrl: str):
        if QueueUrl != self.queue_url:
            raise SqsQueueException(f"Queue URL {QueueUrl} does not match the queue's url ({self.queue_url})")

    def receive_message(
        self, QueueUrl: str, MaxNumberOfMessages: int = 1, WaitTimeSeconds: int = SQS_MAX_WAIT_TIME_SECS, **kwargs
    ) -> dict:
        """Returns message(s) to the caller.

        The messages are a list of dictionaries under a top-level key 'Messages'.
        Even if only one message is requested, 'Messages' is still used.
        """
        self.raise_exception_if_url_not_matching(QueueUrl)

        if MaxNumberOfMessages == 0:
            raise SqsQueueException("receive_message(): MaxNumberOfMessages cannot be 0")

        if WaitTimeSeconds < 0:
            raise SqsQueueException("WaitTimeSeconds must be >= 0")

        desired_num_of_messages = (
            len(self.messages) if MaxNumberOfMessages == -1 else min(MaxNumberOfMessages, len(self.messages))
        )
        tmp_payload = self.messages[:desired_num_of_messages]
        self.messages = self.messages[desired_num_of_messages:]

        # Move all messages into the `received` dictionary,
        # and then create the result dictionaries that each message body sits in
        payload = []
        for msg in tmp_payload:
            handle = self.__get_new_message_handle()
            self.received_messages[handle] = msg
            msg_dict = {
                "MessageId": handle,
                "ReceiptHandle": handle,
                "Body": msg,
                # While the typical response has other fields, we only need the above three
            }
            payload.append(msg_dict)

        # There weren't any messages to deliver,
        # so to approximate SQS's blocking behavior, we sleep
        if len(payload) == 0:
            sleep(WaitTimeSeconds)

        return {"Messages": payload}

    def send_message(self, QueueUrl: str, MessageBody: str):
        """Puts a message into the queue."""
        self.raise_exception_if_url_not_matching(QueueUrl)
        self.messages.append(MessageBody)

    def send_messages(self, QueueUrl: str, MessageBodies: List[str]):
        self.raise_exception_if_url_not_matching(QueueUrl)
        self.messages += MessageBodies

    def delete_message(self, QueueUrl: str, ReceiptHandle: str):
        """Deletes a message from the queue."""
        self.raise_exception_if_url_not_matching(QueueUrl)
        if ReceiptHandle not in self.received_messages:
            raise SqsQueueException(f'Message with receipt handle "{ReceiptHandle}" not found')
        else:
            del self.received_messages[ReceiptHandle]

    def delete_message_batch(self, QueueUrl: str, Entries: list) -> dict:
        """Deletes multiple messages from the queue.

        Returns a response dict with 'Successful' and 'Failed' lists matching
        the AWS SQS API format.
        """
        self.raise_exception_if_url_not_matching(QueueUrl)
        successful = []
        failed = []
        for entry in Entries:
            receipt_handle = entry["ReceiptHandle"]
            entry_id = entry["Id"]
            if receipt_handle in self.received_messages:
                del self.received_messages[receipt_handle]
                successful.append({"Id": entry_id})
            else:
                failed.append(
                    {
                        "Id": entry_id,
                        "Code": "ReceiptHandleNotFound",
                        "Message": f"Receipt handle {receipt_handle} not found",
                    }
                )
        return {"Successful": successful, "Failed": failed}

    def purge_queue(self, QueueUrl: str):
        self.raise_exception_if_url_not_matching(QueueUrl)
        self.messages = []
        self.received_messages = {}

    def len(self) -> int:
        """Returns the number of messages in the queue, awaiting receipt."""
        return len(self.messages)


class SqsQueue:

    APPROX_NUM_OF_MESSAGES = "ApproximateNumberOfMessages"
    CREATED = "CreatedTimestamp"
    LAST_MODIFIED = "LastModifiedTimestamp"

    """Class to represent an SQS queue"""

    def __init__(self, sqs_client, queue_url):
        # CC: According to https://boto3.amazonaws.com/v1/documentation/api/latest/guide/resources.html,
        # CC: we should use clients instead of resources (which was being done previously)
        # CC: For the boto3 reference on clients, see
        # CC: https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/sqs.html
        self.sqs_client = sqs_client
        self.queue_url = queue_url
        self.is_local = isinstance(sqs_client, LocalSqsQueue)
        self.is_aws = not self.is_local
        self.logger = logging.getLogger("SqsQueue")

    def get_messages(
        self, max_num_of_messages: int, wait_time_secs: int = SQS_MAX_WAIT_TIME_SECS
    ) -> List[QueueMessage]:
        """
        Gets up to `max_num_of_messages` messages from the queue.

        If `max_num_of_messages == -1`, then this function polls from the queue
        until it is empty for the first time.

        If the queue is empty (or has fewer than `max_num_of_messages`),
        the function may wait for up to `wait_time_secs`.

        If more than 10 messages are requested, this function loops around
        `receive_message()` until the maximum number is met, since SQS queues
        can deliver at most 10 messages at a time.
        """

        if max_num_of_messages == 0:
            raise SqsQueueException("get_messages(): max_num_of_messages cannot be 0")

        # AWS throws an error if the wait/poll time on a queue exceeds SQS_MAX_WAIT_TIME_SECS
        # So, to flexibly allow wait times longer than that, we split wait times.
        # If the queue gives us a message, fine.
        # If not, we wait the additional time past the max.
        # TODO: Update this when looping multiple times?
        wait_on_queue = min(wait_time_secs, SQS_MAX_WAIT_TIME_SECS)
        wait_after_queue = max(wait_time_secs - SQS_MAX_WAIT_TIME_SECS, 0)
        messages = []

        while max_num_of_messages == -1 or len(messages) < max_num_of_messages:
            if max_num_of_messages == -1:
                desired_num_of_messages = SQS_MAX_MESSAGES_PER_CALL
            else:
                desired_num_of_messages = min(SQS_MAX_MESSAGES_PER_CALL, max_num_of_messages - len(messages))

            try:
                self.logger.info(f"Polling SQS queue {self.queue_url} for {desired_num_of_messages} message(s)")
                response = self.sqs_client.receive_message(
                    QueueUrl=self.queue_url,
                    AttributeNames=["All"],
                    MaxNumberOfMessages=desired_num_of_messages,
                    MessageAttributeNames=["All"],
                    WaitTimeSeconds=wait_on_queue,
                )
            except ClientError as e:
                self.logger.error("Failed to get message from SQS queue")
                self.logger.exception(e)
                raise SqsQueueException(f"Failed to get message from SQS queue {self.queue_url}")

            self.logger.info(f"Received: {response}")
            if (
                response is None
                or len(response) == 0
                or response.get("Messages") is None
                or len(response["Messages"]) == 0
            ):
                sleep(wait_after_queue)
                return messages
            else:
                messages += [QueueMessage(s, self.sqs_client, self.queue_url) for s in response["Messages"]]

        return messages

    def receive_messages(
        self, max_num_of_messages: int, wait_time_secs: int = SQS_MAX_WAIT_TIME_SECS
    ) -> List[QueueMessage]:
        """The same as `get_messages()`."""
        return self.get_messages(max_num_of_messages, wait_time_secs)

    def get_message(self, wait_time_secs: int = SQS_MAX_WAIT_TIME_SECS) -> QueueMessage | None:
        msgs = self.get_messages(1, wait_time_secs)
        return msgs[0] if len(msgs) > 0 else None

    def receive_message(self, wait_time_secs: int = SQS_MAX_WAIT_TIME_SECS) -> QueueMessage | None:
        """Receives a message from the queue. The same as `get_message()`."""
        return self.get_message(wait_time_secs)

    def put_messages(self, messages: List[str], display_progress_bar: bool = False):
        """Put a list of messages on the queue"""
        if len(messages) == 0:
            return

        if self.is_local:
            self.sqs_client.send_messages(self.queue_url, messages)
            return

        # Otherwise, we need to batch them to send to AWS, 10 at a time
        if display_progress_bar:
            from tqdm import tqdm

            t = tqdm(total=len(messages))
        else:
            t = None

        num_sent = 0
        for batch in batched(messages, SQS_BATCH_SIZE):
            l = len(batch)
            try:
                self.logger.info(f"Trying to put {l} message(s) onto queue {self.queue_url}")

                # TODO: Validate that all messages successfully sent?
                self.sqs_client.send_message_batch(
                    QueueUrl=self.queue_url,
                    Entries=[
                        {
                            "Id": f"batched-put-{uuid4()}",
                            "MessageBody": s,
                        }
                        for s in batch
                    ],
                )
            except ClientError as e:
                self.logger.error("Failed to put message on SQS queue")
                self.logger.exception(e)
                raise SqsQueueException(f"Failed to put message on SQS queue {self.queue_url}")

            num_sent += l
            if t is not None:
                t.update(l)

        if t is not None:
            t.close()

    def send_messages(self, messages: List[str], display_progress_bar: bool = False):
        self.put_messages(messages, display_progress_bar)

    def put_message(self, msg: str):
        """Put a single message on the queue"""
        try:
            self.logger.info("Trying to put message onto queue %s", self.queue_url)
            self.sqs_client.send_message(
                QueueUrl=self.queue_url,
                MessageBody=msg,
            )
        except ClientError as e:
            self.logger.error("Failed to put message on SQS queue")
            self.logger.exception(e)
            raise SqsQueueException(f"Failed to put message on SQS queue {self.queue_url}")

    def send_message(self, msg: str):
        """Sends a message to the queue. The same as `put_message()`."""
        self.put_message(msg)

    def purge(self):
        try:
            self.logger.info(f"Trying to purge queue {self.queue_url}")
            self.sqs_client.purge_queue(QueueUrl=self.queue_url)
        except ClientError as e:
            self.logger.error(f"Failed to purge queue {self.queue_url}")
            self.logger.exception(e)
            raise SqsQueueException(f"Failed to purge queue {self.queue_url}")

    def delete_message_batch(self, messages: List[QueueMessage]) -> None:
        """Deletes up to 10 messages from the queue in a single API call.

        Note: Partial failures are logged but do not raise an exception. Messages
        that fail to delete will be redelivered by SQS after the visibility timeout,
        potentially causing duplicate processing. Callers should be idempotent or
        implement deduplication if this is a concern.
        """
        if len(messages) == 0:
            return
        if len(messages) > SQS_MAX_MESSAGES_PER_CALL:
            raise SqsQueueException(
                f"delete_message_batch: cannot delete more than {SQS_MAX_MESSAGES_PER_CALL} messages at once"
            )

        entries = [{"Id": str(i), "ReceiptHandle": msg.get_handle()} for i, msg in enumerate(messages)]
        try:
            response = self.sqs_client.delete_message_batch(
                QueueUrl=self.queue_url,
                Entries=entries,
            )
            failed = response.get("Failed", [])
            if failed:
                # TODO: Consider retry logic or returning failed message IDs to caller
                self.logger.warning(f"Failed to delete {len(failed)} message(s) in batch")
                for f in failed:
                    self.logger.warning(f"  Id={f.get('Id')} Code={f.get('Code')} Msg={f.get('Message')}")
        except ClientError as e:
            self.logger.error("Failed to batch-delete messages from SQS queue")
            self.logger.exception(e)
            raise SqsQueueException(f"Failed to batch-delete messages on SQS queue {self.queue_url}")

    def len(self) -> int:
        if self.is_local:
            return self.sqs_client.len()
        else:
            response = self.sqs_client.get_queue_attributes(
                QueueUrl=self.queue_url,
                AttributeNames=[self.APPROX_NUM_OF_MESSAGES],
            )

            return int(response["Attributes"][self.APPROX_NUM_OF_MESSAGES])

    def created(self) -> str:
        if self.is_local:
            return "NOT YET IMPLEMENTED"
        else:
            response = self.sqs_client.get_queue_attributes(
                QueueUrl=self.queue_url,
                AttributeNames=[self.CREATED],
            )

            return strftime("%Y-%m-%d %H:%M:%S", localtime(int(response["Attributes"][self.CREATED])))

    def last_modified(self) -> str:
        if self.is_local:
            return "NOT YET IMPLEMENTED"
        else:
            response = self.sqs_client.get_queue_attributes(
                QueueUrl=self.queue_url,
                AttributeNames=[self.LAST_MODIFIED],
            )

            return strftime("%Y-%m-%d %H:%M:%S", localtime(int(response["Attributes"][self.LAST_MODIFIED])))

    def get_attributes(self) -> dict:
        if self.is_local:
            return {}
        else:
            response = self.sqs_client.get_queue_attributes(
                QueueUrl=self.queue_url, AttributeNames=[self.APPROX_NUM_OF_MESSAGES, self.CREATED, self.LAST_MODIFIED]
            )

            num_msgs = int(response["Attributes"][self.APPROX_NUM_OF_MESSAGES])
            created = strftime("%Y-%m-%d %H:%M:%S", localtime(int(response["Attributes"][self.CREATED])))
            # modified = strftime('%Y-%m-%d %H:%M:%S', localtime(int(response['Attributes'][self.LAST_MODIFIED])))

            return {
                self.APPROX_NUM_OF_MESSAGES: num_msgs,
                self.CREATED: created,
                # self.LAST_MODIFIED: modified,
            }

    @staticmethod
    def get_sqs_queue_url(queue_name: str) -> "SqsQueue":
        sqs_client = boto3.client("sqs")
        queue_url = sqs_client.get_queue_url(QueueName=queue_name)["QueueUrl"]
        return SqsQueue(sqs_client, queue_url)

    @staticmethod
    def get_sqs_queue_from_session(session: boto3.Session, queue_name: str) -> "SqsQueue":
        sqs_client = session.client("sqs")
        queue_url = sqs_client.get_queue_url(QueueName=queue_name)["QueueUrl"]
        return SqsQueue(sqs_client, queue_url)

    @staticmethod
    def get_local_sqs_queue(queue_name: str) -> "SqsQueue":
        sqs_client = LocalSqsQueue(queue_name)
        queue_url = sqs_client.get_queue_url()
        return SqsQueue(sqs_client, queue_url)

    @staticmethod
    def get_queues_from_env(senv: SolverEnvironment) -> Tuple["SqsQueue", "SqsQueue"]:
        rn = senv.to_resource_namer()
        input_queue_name = rn.get_sqs_input_queue_name()
        output_queue_name = rn.get_sqs_output_queue_name()
        if senv.is_local:
            q_in = SqsQueue.get_local_sqs_queue(input_queue_name)
            q_out = SqsQueue.get_local_sqs_queue(output_queue_name)
        else:
            q_in = SqsQueue.get_sqs_queue_url(input_queue_name)
            q_out = SqsQueue.get_sqs_queue_url(output_queue_name)
        return q_in, q_out
