#!/bin/bash
echo "This is a test! Here is what the log would look like"
echo " \
{
  \"artifacts\": {
    \"stdout_path\": \"$1/solver_stdout.log\",
    \"stderr_path\": \"$1/solver_stderr.log\"
  }
}
" > $1/solver_out.json

echo "This is the stdout log" >> $1/solver_stdout.log
echo "This is the stderr log" >> $1/solver_stderr.log
