class DistributedConsts:
    HEARTBEAT_SLEEP_INTERVAL = 2
    LEADER_CLAIM_WORKERS_SLEEP_INTERVAL = 5
    LED_BY_SLEEP_INTERVAL = 1
    CLEAN_SLEEP_INTERVAL = 2
    CLEANUP_TIMEOUT_SECS = 5
    ALLOWED_MISSED_LEADER_HEARTBEATS = 3
    HEARTBEAT_ERROR_SECS = ALLOWED_MISSED_LEADER_HEARTBEATS * HEARTBEAT_SLEEP_INTERVAL
